import Home from '@/components/pages/home'
import Head from 'next/head'
export default function HomePage() {
  return (
    <>
      <Head>
        <title>iVREAD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ivread.png" />
      </Head>
      <Home />
    </>
  )
}
